(()=>{const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let D,P,G,pending;const show=id=>{["platforms","games","detail"].forEach(x=>$("#"+x).hidden=x!==id);scrollTo(0,0)},score=n=>(n>0?"+":"")+n+"/20";
function platforms(){platformGrid.innerHTML=D.platforms.map(p=>`<button class="v3platform" data-p="${p.id}"><div class="consolepic">${p.short}</div><small>${p.family}</small><h3>${p.name}</h3><p>${D.games.filter(g=>g.platform===p.id).length} jeu(x) dans la maquette</p><b>Voir la collection →</b></button>`).join("");$$("[data-p]").forEach(b=>b.onclick=()=>openP(b.dataset.p))}
function openP(id){P=D.platforms.find(x=>x.id===id);family.textContent=P.family;consoleName.textContent=P.name;renderGames();show("games")}
function renderGames(){let a=D.games.filter(g=>g.platform===P.id),q=searchGame.value.toLowerCase();if(q)a=a.filter(g=>g.title.toLowerCase().includes(q));a.sort((a,b)=>a.title.localeCompare(b.title)*(sort.value==="az"?1:-1));gameCount.textContent=D.games.filter(g=>g.platform===P.id).length+" jeux dans cette maquette";gameGrid.innerHTML=a.map(g=>`<button class="v3game" data-g="${g.id}"><div class="cover">${g.title}</div><h3>${g.title}</h3><p>${g.short}</p></button>`).join("")||'<p class="collection-empty">Aucun jeu dans la démo.</p>';$$("[data-g]").forEach(b=>b.onclick=()=>openG(b.dataset.g))}
function openG(id){G=D.games.find(x=>x.id===id);detailPlatform.textContent=P.name;detailTitle.textContent=G.title;bigCover.textContent=G.title;short.textContent=G.short;facts.innerHTML=[["Année",G.year],["Genre",G.genre],["Développeur",G.developer],["Éditeur",G.publisher]].map(x=>`<div><span>${x[0]}</span><b>${x[1]}</b></div>`).join("");description.textContent=G.description;score.textContent=window.score?window.score(G.score):(G.score>0?"+":"")+G.score+"/20";myfacts.innerHTML=[["Région",G.region],["État",G.condition],["Version",G.version]].map(x=>`<div><span>${x[0]}</span><b>${x[1]}</b></div>`).join("");opinion.textContent=G.opinion;anecdote.textContent=G.anecdote;show("detail")}
function modal(title,body){modalTitle.textContent=title;modalBody.innerHTML=body;modal.hidden=false;document.body.classList.add("modal-open")}
function shut(){modal.hidden=true;document.body.classList.remove("modal-open")}
addConsole.onclick=()=>modal("Choisir une console",`<p class="modalintro">Simulation du futur catalogue de consoles.</p><div class="dbresults">${D.dbPlatforms.map(p=>`<button data-ap="${p.id}"><div>${p.short}</div><span><small>${p.family}</small><b>${p.name}</b></span><strong>Ajouter</strong></button>`).join("")}</div>`);modalBody.onclick=e=>{let b=e.target.closest("[data-ap]");if(!b)return;let p=D.dbPlatforms.find(x=>x.id===b.dataset.ap);D.platforms.push(p);D.dbPlatforms=D.dbPlatforms.filter(x=>x.id!==p.id);shut();platforms()}
addGame.onclick=()=>modal("Rechercher dans la base",`<p class="modalintro">Dans la version finale, ces résultats viendront automatiquement d'une base de jeux.</p><div class="dbresults">${D.dbGames.map((g,i)=>`<button data-ag="${i}"><div class="miniCover">${g.title[0]}</div><span><small>${g.year} • ${g.genre}</small><b>${g.title}</b><em>${g.short}</em></span><strong>Sélectionner</strong></button>`).join("")}</div>`);modalBody.addEventListener("click",e=>{let b=e.target.closest("[data-ag]");if(!b)return;pending=D.dbGames[+b.dataset.ag];modal("Compléter mon exemplaire",form(pending))});
function form(g){return `<div class="prefill">✓ Titre, année, genre, développeur et éditeur sont déjà préremplis.</div><form id="mineForm"><div class="form-two"><label>Région<select name="region"><option>PAL</option><option>JAP</option><option>US</option></select></label><label>État<select name="condition"><option>Complet</option><option>Boîte</option><option>Loose</option></select></label></div><label>Version<input name="version" placeholder="PAL FR, Platinum…"></label><label>Ma note : <b id="sv">+15/20</b><input id="slider" name="score" type="range" min="-20" max="20" value="15"></label><label>Mon avis<textarea name="opinion" rows="4"></textarea></label><label class="anecdoteInput">Anecdote<textarea name="anecdote" rows="4"></textarea></label><button class="admin-primary" type="submit">Ajouter à ma collection</button></form>`}
modalBody.addEventListener("input",e=>{if(e.target.id==="slider")sv.textContent=(e.target.value>0?"+":"")+e.target.value+"/20"});modalBody.addEventListener("submit",e=>{if(e.target.id!=="mineForm")return;e.preventDefault();let f=new FormData(e.target),g={...pending,id:"x"+Date.now(),platform:P.id,region:f.get("region"),condition:f.get("condition"),version:f.get("version"),score:+f.get("score"),opinion:f.get("opinion"),anecdote:f.get("anecdote"),description:"Description automatiquement récupérée dans la future version."};D.games.push(g);shut();renderGames();show("games")});
editGame.onclick=()=>modal("Modifier ma fiche",form(G));backPlatforms.onclick=()=>show("platforms");backGames.onclick=()=>show("games");searchGame.oninput=renderGames;sort.onchange=renderGames;close.onclick=shut;modal.onclick=e=>{if(e.target===modal)shut()};
fetch("data/collections-v3-demo.json").then(r=>r.json()).then(d=>{D=d;platforms()})})();