(function(){
  const treasureKey = "legaia_treasures_v1";
  const objectiveKey = "legaia_objectives_v1";
  const treasureInputs = Array.from(document.querySelectorAll('input[data-tracker="treasure"]'));
  const objectiveInputs = Array.from(document.querySelectorAll('input[data-tracker="objective"]'));
  if (!treasureInputs.length && !objectiveInputs.length) return;
  function load(key){ try { return JSON.parse(localStorage.getItem(key) || '[]'); } catch(e){ return []; } }
  function save(key, values){ localStorage.setItem(key, JSON.stringify(values)); }
  function applyState(inputs, checkedValues){ const set = new Set(checkedValues); inputs.forEach(input => { input.checked = set.has(input.value); }); }
  function currentValues(inputs){ return inputs.filter(i => i.checked).map(i => i.value); }
  function updateGroupCounts(){ document.querySelectorAll('.tracker-checklist[data-group]').forEach(group => { const id = group.dataset.group; const inputs = Array.from(group.querySelectorAll('input[type="checkbox"]')); const checked = inputs.filter(i => i.checked).length; const badge = document.querySelector('[data-count-for="' + id + '"]'); if (badge) badge.textContent = `${checked} / ${inputs.length}`; }); }
  function updateTotals(){ const treasureChecked = treasureInputs.filter(i => i.checked).length; const objectiveChecked = objectiveInputs.filter(i => i.checked).length; const treasureCount = document.getElementById('treasure-overall-count'); const treasureBar = document.getElementById('treasure-overall-bar'); const objectiveCount = document.getElementById('objective-overall-count'); const objectiveBar = document.getElementById('objective-overall-bar'); if (treasureCount) treasureCount.textContent = `${treasureChecked} / ${treasureInputs.length} trouvés`; if (treasureBar) treasureBar.style.width = `${treasureInputs.length ? (treasureChecked / treasureInputs.length) * 100 : 0}%`; if (objectiveCount) objectiveCount.textContent = `${objectiveChecked} / ${objectiveInputs.length} validés`; if (objectiveBar) objectiveBar.style.width = `${objectiveInputs.length ? (objectiveChecked / objectiveInputs.length) * 100 : 0}%`; updateGroupCounts(); }
  function persist(){ save(treasureKey, currentValues(treasureInputs)); save(objectiveKey, currentValues(objectiveInputs)); updateTotals(); }
  applyState(treasureInputs, load(treasureKey)); applyState(objectiveInputs, load(objectiveKey)); updateTotals(); [...treasureInputs, ...objectiveInputs].forEach(input => input.addEventListener('change', persist)); const resetTreasures = document.getElementById('reset-treasures-btn'); if (resetTreasures) resetTreasures.addEventListener('click', () => { treasureInputs.forEach(i => i.checked = false); save(treasureKey, []); updateTotals(); }); const resetAll = document.getElementById('reset-all-btn'); if (resetAll) resetAll.addEventListener('click', () => { treasureInputs.forEach(i => i.checked = false); objectiveInputs.forEach(i => i.checked = false); save(treasureKey, []); save(objectiveKey, []); updateTotals(); });})();
